from __future__ import annotations

import argparse
import html
import json
import re
import shutil
import sys
import time
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

try:
    import pymupdf
except ImportError:  # pragma: no cover
    import fitz as pymupdf


NUMBERED_DIR_PATTERN = re.compile(r"^(\d{2})-")
TITLE_FRONTMATTER_PATTERN = re.compile(r"(?ms)^---\s*\n.*?^title:\s*[\"']?(.*?)[\"']?\s*$.*?^---\s*$")


@dataclass(frozen=True)
class Paths:
    repo_root: Path
    inbox: Path
    archive: Path
    rejected: Path
    knowledge_root: Path


def resolve_paths() -> Paths:
    repo_root = Path(__file__).resolve().parent.parent
    return Paths(
        repo_root=repo_root,
        inbox=repo_root / "pdf-to-images" / "inbox",
        archive=repo_root / "pdf-to-images" / "archive",
        rejected=repo_root / "pdf-to-images" / "rejected",
        knowledge_root=repo_root / "docs" / "05-Guides",
    )


def slugify(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^A-Za-z0-9]+", "-", ascii_value).strip("-").lower()
    return slug or "document"


def derive_title(pdf_path: Path, metadata: dict[str, object]) -> str:
    raw_title = str(metadata.get("title") or "").strip()
    if raw_title:
        return raw_title

    stem = pdf_path.stem.replace("_", " ")
    stem = re.sub(r"^[0-9]+[-_ ]*", "", stem)
    stem = re.sub(r"\s+", " ", stem).strip()
    return stem or pdf_path.stem


def next_entry_number(knowledge_root: Path) -> int:
    highest = 0
    for path in knowledge_root.iterdir():
        if not path.is_dir():
            continue
        match = NUMBERED_DIR_PATTERN.match(path.name)
        if match:
            highest = max(highest, int(match.group(1)))
    return highest + 1


def choose_entry_dir(knowledge_root: Path, title: str) -> Path:
    number = next_entry_number(knowledge_root)
    slug = slugify(title)
    while True:
        candidate = knowledge_root / f"{number:02d}-{slug}"
        if not candidate.exists():
            return candidate
        number += 1


def list_ready_pdfs(inbox: Path, stability_window: float) -> list[Path]:
    now = time.time()
    pdfs = []
    for path in sorted(inbox.iterdir()):
        if not path.is_file() or path.suffix.lower() != ".pdf":
            continue
        age_seconds = now - path.stat().st_mtime
        if age_seconds >= stability_window:
            pdfs.append(path)
    return pdfs


def render_pages(document: pymupdf.Document, images_dir: Path, zoom: float) -> list[dict[str, object]]:
    images = []
    matrix = pymupdf.Matrix(zoom, zoom)
    for page_number, page in enumerate(document, start=1):
        image_name = f"page-{page_number:03d}.png"
        image_path = images_dir / image_name
        pixmap = page.get_pixmap(matrix=matrix, alpha=False)
        pixmap.save(image_path)
        images.append(
            {
                "page": page_number,
                "file": image_name,
                "text": page.get_text("text").strip(),
            }
        )
    return images


def build_searchable_text_block(page_number: int, page_text: str) -> list[str]:
    if not page_text.strip():
        return []

    escaped_text = html.escape(page_text)
    return [
        f"<details class=\"page-search-text\">",
        f"<summary>Raw text - page {page_number}</summary>",
        "",
        "<pre>",
        escaped_text,
        "</pre>",
        "</details>",
        "",
    ]


def write_markdown(page_path: Path, title: str, source_pdf_name: str, rendered_pages: list[dict[str, object]]) -> None:
    title_literal = title.replace('"', '\\"')
    lines = [
        "---",
        f'title: "{title_literal}"',
        "---",
        "",
        f"# {title}",
        "",
        f"- Source PDF: `{source_pdf_name}`",
        f"- Rendered pages: {len(rendered_pages)}",
        "- Generated by: `pdf-to-images/process_inbox.py`",
        "",
        "## Editorial summary",
        "",
        "Add a concise reviewed summary here before publishing this page as curated knowledge.",
        "",
        "## Page images",
        "",
    ]

    for page in rendered_pages:
        page_number = int(page["page"])
        image_name = str(page["file"])
        lines.extend(
            [
                f"### Page {page_number}",
                "",
                f"![Page {page_number}](images/{image_name})",
                "",
            ]
        )
        lines.extend(build_searchable_text_block(page_number, str(page["text"])))

    page_path.write_text("\n".join(lines), encoding="utf-8")


def write_pages_config(output_dir: Path, title: str) -> None:
    title_literal = title.replace('"', '\\"')
    pages_content = "\n".join(
        [
            "title: \"" + title_literal + "\"",
            "nav:",
            "  - index.md",
            "",
        ]
    )
    (output_dir / ".pages").write_text(pages_content, encoding="utf-8")


def extract_markdown_title(index_path: Path) -> str | None:
    if not index_path.exists():
        return None

    content = index_path.read_text(encoding="utf-8")
    match = TITLE_FRONTMATTER_PATTERN.search(content)
    if match:
        candidate = match.group(1).strip()
        return candidate or None

    for line in content.splitlines():
        if line.startswith("# "):
            candidate = line[2:].strip()
            return candidate or None

    return None


def sync_pages_title_for_folder(folder_path: Path) -> bool:
    index_path = folder_path / "index.md"
    title = extract_markdown_title(index_path)
    if not title:
        return False

    pages_path = folder_path / ".pages"
    expected_content = "\n".join(
        [
            f'title: "{title.replace("\"", "\\\\\"")}"',
            "nav:",
            "  - index.md",
            "",
        ]
    )

    if pages_path.exists() and pages_path.read_text(encoding="utf-8") == expected_content:
        return False

    pages_path.write_text(expected_content, encoding="utf-8")
    return True


def sync_existing_pages_titles(knowledge_root: Path) -> int:
    updated = 0
    for path in sorted(knowledge_root.iterdir()):
        if path.is_dir() and (path / "index.md").exists():
            if sync_pages_title_for_folder(path):
                updated += 1
    return updated


def move_with_retries(source: Path, destination: Path, attempts: int = 5, delay_seconds: float = 0.5) -> None:
    last_error: Exception | None = None
    for attempt in range(1, attempts + 1):
        try:
            shutil.move(str(source), str(destination))
            return
        except PermissionError as exc:
            last_error = exc
            if attempt == attempts:
                break
            time.sleep(delay_seconds * attempt)

    raise RuntimeError(
        f"Could not move '{source.name}' to '{destination.parent.name}' after {attempts} attempts. "
        "The file is still locked by another process."
    ) from last_error


def archive_pdf(source: Path, archive_dir: Path) -> Path:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    target = archive_dir / f"{timestamp}-{source.name}"
    counter = 1
    while target.exists():
        target = archive_dir / f"{timestamp}-{counter:02d}-{source.name}"
        counter += 1
    move_with_retries(source, target)
    return target


def reject_pdf(source: Path, rejected_dir: Path) -> Path:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    target = rejected_dir / f"{timestamp}-{source.name}"
    counter = 1
    while target.exists():
        target = rejected_dir / f"{timestamp}-{counter:02d}-{source.name}"
        counter += 1
    move_with_retries(source, target)
    return target


def process_pdf(pdf_path: Path, paths: Paths, zoom: float) -> dict[str, object]:
    output_dir: Path | None = None
    document = None
    try:
        document = pymupdf.open(pdf_path)
        title = derive_title(pdf_path, document.metadata or {})
        output_dir = choose_entry_dir(paths.knowledge_root, title)
        images_dir = output_dir / "images"
        images_dir.mkdir(parents=True, exist_ok=False)

        rendered_pages = render_pages(document, images_dir, zoom)
        if not rendered_pages:
            raise ValueError("The PDF has no renderable pages.")

        extracted_text = "\n\n".join(
            f"--- Page {page['page']:03d} ---\n{page['text']}" for page in rendered_pages
        )
        (output_dir / "extracted-text.txt").write_text(extracted_text, encoding="utf-8")

        manifest = {
            "source_pdf": pdf_path.name,
            "title": title,
            "page_count": len(rendered_pages),
            "processed_at": datetime.now(timezone.utc).isoformat(),
            "images": [{"page": page["page"], "file": page["file"]} for page in rendered_pages],
            "pdf_metadata": document.metadata,
        }
        (output_dir / "manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=True),
            encoding="utf-8",
        )

        write_markdown(output_dir / "index.md", title, pdf_path.name, rendered_pages)
        write_pages_config(output_dir, title)

        document.close()
        document = None

        archived_pdf = archive_pdf(pdf_path, paths.archive)
        manifest["archived_pdf"] = str(archived_pdf.relative_to(paths.repo_root)).replace("\\", "/")
        (output_dir / "manifest.json").write_text(
            json.dumps(manifest, indent=2, ensure_ascii=True),
            encoding="utf-8",
        )

        return {
            "status": "processed",
            "source": pdf_path.name,
            "title": title,
            "output": str(output_dir.relative_to(paths.repo_root)).replace("\\", "/"),
        }
    except Exception as exc:
        if document is not None:
            document.close()
            document = None
        if output_dir and output_dir.exists():
            shutil.rmtree(output_dir)

        rejected_pdf: Path | None = None
        rejection_reason = str(exc)
        if pdf_path.exists():
            try:
                rejected_pdf = reject_pdf(pdf_path, paths.rejected)
            except Exception as reject_exc:
                rejection_reason = f"{rejection_reason}; cleanup move failed: {reject_exc}"

        return {
            "status": "rejected",
            "source": pdf_path.name,
            "reason": rejection_reason,
            "rejected": (
                str(rejected_pdf.relative_to(paths.repo_root)).replace("\\", "/") if rejected_pdf else None
            ),
        }
    finally:
        if document is not None:
            document.close()


def process_inbox(paths: Paths, zoom: float, stability_window: float) -> list[dict[str, object]]:
    paths.archive.mkdir(parents=True, exist_ok=True)
    paths.rejected.mkdir(parents=True, exist_ok=True)
    paths.knowledge_root.mkdir(parents=True, exist_ok=True)

    sync_existing_pages_titles(paths.knowledge_root)

    results = []
    for pdf_path in list_ready_pdfs(paths.inbox, stability_window):
        results.append(process_pdf(pdf_path, paths, zoom))
    return results


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert PDFs from pdf-to-images/inbox into reviewed knowledge page scaffolds."
    )
    parser.add_argument("--watch", action="store_true", help="Keep watching the inbox for new PDFs.")
    parser.add_argument(
        "--interval",
        type=float,
        default=10.0,
        help="Polling interval in seconds when --watch is enabled.",
    )
    parser.add_argument(
        "--stability-window",
        type=float,
        default=5.0,
        help="Ignore PDFs modified within the last N seconds.",
    )
    parser.add_argument(
        "--zoom",
        type=float,
        default=2.0,
        help="Rendering zoom factor for page images.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    paths = resolve_paths()

    while True:
        results = process_inbox(paths, zoom=args.zoom, stability_window=args.stability_window)
        if results:
            for result in results:
                if result["status"] == "processed":
                    print(f"Processed {result['source']} -> {result['output']}")
                else:
                    print(
                        f"Rejected {result['source']} -> {result['rejected']} ({result['reason']})",
                        file=sys.stderr,
                    )
        elif not args.watch:
            print("No ready PDF files found in pdf-to-images/inbox.")

        if not args.watch:
            rejected_count = sum(1 for result in results if result["status"] == "rejected")
            return 1 if rejected_count else 0

        time.sleep(args.interval)


if __name__ == "__main__":
    raise SystemExit(main())